# Generated by Django 6.1 on 2026-08-13 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rentals",
            old_name="vehicle_id",
            new_name="vehicle",
        ),
    ]
